ApproverNEW/urls.py
#-*- coding: utf-8 -*-
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include, url
from core.views import MainView
from django.conf.urls.static import static
from django.conf import settings

admin.autodiscover()

urlpatterns = [
    url(r'^kredit/', include('kredit.urls')),
    url(r'^core/', include('core.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', MainView.as_view(), name='main_view'),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]
# static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
# -*- coding: utf-8 -*-
__author__ = 'kvn'
from django.conf.urls import url
from views import LoginFormView, LogoutView

urlpatterns = [
    url(r'^login/$', LoginFormView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
]

kredit/urls.py
# -*- coding: utf-8 -*-
__author__ = 'kvn'
from django.conf.urls import url
from views import KreditList, KreditRequest, MyKredits, SearchKredit, GroupKredits,KreditDetail

urlpatterns = [
    url(r'^group/(?P<group>\w+)/', GroupKredits.as_view(), name='by_group'),
    url(r'^search/', SearchKredit.as_view(), name='search'),
    url(r'^my/(?P<group>\w+)/', MyKredits.as_view(), name='my_kredits'),
    url(r'^request/', KreditRequest.as_view(), name='kredit_request'),
    url(r'^list/$', KreditList.as_view(), name='kredit_list'),
    url(r'^detail/(?P<pk>\d+)/$', KreditDetail.as_view(), name='kredit_detail'),
]

kredit/models.py
#-*- coding: utf-8 -*-
from __future__ import unicode_literals

import os
from django.db import models
from Bank.models import Office
from django.contrib.auth.models import Group, User
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible
from django.db.models.signals import post_save
from django.dispatch import receiver



@python_2_unicode_compatible
class Kredit(models.Model):
    COMPLECT1 = ['kredit_user', 'kredit_approver']
    #COMPLECT2 = ['kredit_user', 'kredit_approver', ['DB_Dagestan', 'DB_Moscow', 'DB_SKFO'], 'kredit_dskp']
    COMPLECT2 = ['kredit_user', 'kredit_approver', 'kredit_dskp']

    FIRST_COMPLECT = '1'
    SECOND_COMPLECT = '2'
    COMPLECT = (
        (FIRST_COMPLECT, 'первый'),
        (SECOND_COMPLECT, 'второй'),
    )
    KREDIT = (
        ('A', 'ЭКСПРЕСС-НАЛИЧНЫМИ'),
        ('B', 'НАШ ПЕНСИОНЕР'),
        ('C', 'НБКИ')
    )
    STATUS_NEW = 'N'
    STATUS_DISCARD = 'D'
    STATUS_APPROVE = 'A'
    STATUS_REVIEW = 'R'
    STATUS_TRANSFER = 'T'
    STATUS_REWRITE = 'B'
    STATUS_APPRREWRITE = 'C'
    STATUS_DONE = 'F'
    STATUS_MIDREWRITE = 'M'
    STATUS = (
        (STATUS_NEW, 'Новая'),
        (STATUS_DISCARD, 'Отклонена'),
        (STATUS_APPROVE, 'Одобрена'),
        (STATUS_REVIEW, 'На рассмотрении'),
        (STATUS_TRANSFER, 'В процессе передачи'),
        (STATUS_REWRITE, 'Отправлено на доработку'),
        (STATUS_APPRREWRITE, 'На доработку согласователю'),
        (STATUS_DONE, 'Доработано'),
        (STATUS_MIDREWRITE, 'Промежуточная доработка'),
    )
    APPR_STATUS = (
        ('0', 'Решения нет'),
        ('A', 'Одобрен'),
        ('R', 'Отклонен'),
    )
    LEVELS = (
        ('0', 'Кредитчики'),
        ('1', 'Согласователи'),
        ('2', 'Безопасность'),
        ('3', 'ДСКП Выдача'),
    )

    office = models.ForeignKey(Office, verbose_name=_('Office'))
    name = models.CharField(max_length=512, verbose_name=_('Name'), default='')
    surname = models.CharField(max_length=512, verbose_name=_('Surname'), default='')
    secondname = models.CharField(max_length=512, verbose_name=_('Second Name'), default='')
    user = models.ForeignKey(User, verbose_name=_('Employee'))
    sum = models.FloatField(verbose_name=_('Sum'), default=0)
    doc_complect = models.CharField(max_length=1, choices=COMPLECT, default='1', verbose_name=_('Complect'))
    kred_mode = models.CharField(max_length=1, choices=KREDIT, default='A', verbose_name=_('Kredit kind'))
    kred_comment = models.TextField(null=True, blank=True, verbose_name=_('Comment'))
    creation_date = models.DateTimeField(auto_now_add=True, verbose_name=_('Creation data'))
    status = models.CharField(max_length=1, choices=STATUS, default='N', verbose_name=_('Kredit status'))
    link = models.ForeignKey('self', null=True, blank=True, verbose_name=_('Link to other complect'))
    current_level = models.CharField(max_length=1, choices=LEVELS, default='0', verbose_name=_('Level'))
    db_status = models.CharField(max_length=1, choices=APPR_STATUS, default='0', verbose_name=_('DB status'))
    dskp_status = models.CharField(max_length=1, choices=APPR_STATUS, default='0', verbose_name=_('DSKP status'))
    groups = models.ManyToManyField(Group, blank=True, null=True, verbose_name=_('Groups'))

    sess = models.CharField(max_length=64, null=True, blank=True, verbose_name=_('Session'))

    def get_cur_route(self):
        return KreditRoute.objects.filter(kredit=self).order_by('id').last()

    class Meta:
        ordering = ['-id']
        verbose_name = _('Kredit')
        verbose_name_plural = _('Kredits')

    def __str__(self):
        return '{id} {surn} {name} {second}'.format(id=self.id, surn=self.surname, name=self.name, second=self.secondname)

@python_2_unicode_compatible
class KreditRoute(models.Model):
    color = models.CharField(max_length=16, verbose_name=_('Color'), default="black")
    kredit = models.ForeignKey(Kredit)
    creation_date = models.DateTimeField(auto_now_add=True, verbose_name=_('Creation date'))
    stage = models.IntegerField(verbose_name=_('Stage'), default=0)
    prev_group = models.ForeignKey(Group, related_name='kreditroute_prevgroup', null=True, blank=True,
                                   verbose_name=_('Previous group'))
    cur_group = models.ForeignKey(Group, related_name='kreditroute_curgroup', null=True, blank=True,
                                  verbose_name=_('Current group'))
    next_group = models.ForeignKey(Group, related_name='kreditroute_nextgroup', null=True, blank=True,
                                   verbose_name=_('Next group'))
    cur_user = models.ForeignKey(User, related_name='kreditroute_curuser', null=True, blank=True,
                                 verbose_name=_('Current user'))
    comment = models.TextField(verbose_name=_('Comment'), null=True, blank=True)
    blinded_comment = models.TextField(verbose_name=_('Blinded comment'), null=True, blank=True)
    hide_comment = models.BooleanField(verbose_name=_('Hide comment'), default=False)
    session = models.CharField(max_length=64, null=True, blank=True)

    def related_files(self):
        return SessionFiles.objects.filter(sess=self.session)

    def __str__(self):
        return '{id}_{route}_{date}'.format(date=self.creation_date.strftime('%d.%m.%Y %H:%M'), route=self.id,
                                            id=self.kredit.id)

    class Meta:
        verbose_name = _('Kredit route')
        verbose_name_plural = _('Kredit routes')

class SessionFiles(models.Model):
    sess = models.CharField(max_length=64, null=True, blank=True)
    path_to = models.FileField(upload_to='files/%Y/%m/%d/', null=True, blank=True)
    added = models.DateTimeField(auto_now_add=True)


    def extension(self):
        name, extension = os.path.splitext(self.path_to.name)
        return extension[1:] if len(extension) > 1 else extension

    def __unicode__(self):
        return str(self.id)


@receiver(post_save, sender=Kredit)
def kredit_post_init(instance, **kwargs):
    if instance.doc_complect == Kredit.FIRST_COMPLECT:
        my_complect = Kredit.COMPLECT1
    else:
        my_complect = Kredit.COMPLECT2
    my_route,res = KreditRoute.objects.get_or_create(
        kredit=instance,
        cur_group=Group.objects.get(name=my_complect[0]),
        next_group=Group.objects.get(name=my_complect[1]),
        comment=_('New credit was created'),
        cur_user=instance.user,
    )
    my_route.save()

kredit/views.py
#-*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible
from django.shortcuts import render
from django.conf import settings
import uuid
from django.contrib.auth.models import User, Group
from django.views.generic import View, TemplateView, FormView, ListView, DetailView, UpdateView, DeleteView, CreateView
from django.views.generic.edit import FormMixin
from django.views.generic.detail import SingleObjectMixin
from models import Kredit, SessionFiles, KreditRoute
from django.contrib import messages
from core.abstract import SettingsToContext, LoginRequiredMixin
from forms import KreditForm, SessionFilesForm, KreditControlForm
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse_lazy
from django.db.models import Q
from django.core.urlresolvers import reverse_lazy, reverse

class BagesMixin(View):

    def get_context_data(self, **kwargs):
        context = super(BagesMixin, self).get_context_data(**kwargs)
        if Group.objects.get(name=settings.ADMIN_APPROVER) in self.request.user.groups.all() or \
            Group.objects.get(name=settings.FIRST_LINE_APPROVER) in self.request.user.groups.all() or \
            Group.objects.get(name=settings.SECOND_LINE_APPROVER) in self.request.user.groups.all():
            context['all_requests'] = Kredit.objects.all().count()
            context['new_requests'] = Kredit.objects.filter(
                groups__name=settings.FIRST_LINE_APPROVER
            ).filter(status__in=[Kredit.STATUS_NEW, Kredit.STATUS_DONE]).count()
        elif Group.objects.get(name=settings.CREATOR_GROUP) in self.request.user.groups.all():
            context['my_requests'] = Kredit.objects.filter(user=self.request.user).count()
        return context


class KreditList(LoginRequiredMixin, SettingsToContext, BagesMixin, ListView):
    template_name = 'kredit_list.html'
    model = Kredit
    paginate_by = settings.UNITS_PER_PAGE


class KreditDetail(LoginRequiredMixin,  SingleObjectMixin, SettingsToContext, BagesMixin, FormView):
    template_name = 'kredit_detail.html'
    model = Kredit
    form_class = KreditControlForm


    def get_context_data(self, **kwargs):
        self.object = self.model.objects.get(pk=self.kwargs.get('pk'))
        context = super(KreditDetail, self).get_context_data(**kwargs)
        # self.obj = self.model.objects.get(pk=self.kwargs.get('pk'))
        my_sess = uuid.uuid1()
        context['files'] = SessionFiles.objects.filter(sess=self.object.sess)
        context['routes'] = KreditRoute.objects.filter(kredit=self.object).order_by('id')
        context['settings'] = settings
        context['form'] = KreditControlForm(initial={'sess': my_sess})
        if self.object.status in (Kredit.STATUS_DISCARD, Kredit.STATUS_APPROVE):
            context['finish'] = True
        else:
            context['finish'] = False
        return context

    def post(self, request, *args, **kwargs):
        if request.FILES:
            my_file = SessionFiles(path_to=request.FILES.get('file'), sess=request.POST.get('sess'))
            my_file.save()


        self.object = self.get_object()
        prev_route = self.object.get_cur_route()

        # Просто комментарий
        if 'commentButton' in request.POST.keys():
            my_route = KreditRoute.objects.create(
                color='#32c8de',
                kredit=self.object,
                stage=prev_route.stage,
                prev_group=prev_route.prev_group,
                cur_group=prev_route.cur_group,
                next_group=prev_route.next_group,
                cur_user=request.user,
                comment=request.POST.get('comment', ''),
                session=request.POST.get('sess', '')
            )
            my_route.save()
        elif 'takeButton' in request.POST.keys():
            my_route = KreditRoute.objects.create(
                color='#32c8de',
                kredit=self.object,
                stage=prev_route.stage,
                prev_group=prev_route.cur_group,
                cur_group=prev_route.next_group,
                next_group=prev_route.next_group,
                cur_user=request.user,
                blinded_comment=_('User from group %s take credit for review') % prev_route.next_group.name,
                comment=_('User %s take credit for review') % request.user.get_full_name(),
                session=request.POST.get('sess', '')
            )
            my_route.save()
        elif 'improveButton' in request.POST.keys():
            pass
        elif 'acceptButton' in request.POST.keys():
            if self.object.doc_complect == self.object.FIRST_COMPLECT:
                self.object.status = self.object.STATUS_APPROVE
                my_route = KreditRoute.objects.create(
                    color='#5cb85c',
                    kredit=self.object,
                    stage=0,
                    prev_group=prev_route.cur_group,
                    cur_group=prev_route.cur_group,
                    next_group=prev_route.next_group,
                    cur_user=request.user,
                    comment=request.POST.get('comment', ''),
                    session=request.POST.get('sess', '')
                )
                my_route.save()
                self.object.save(update_fields=['status'])
        elif 'declineButton' in request.POST.keys():
            if self.object.doc_complect == self.object.FIRST_COMPLECT:
                self.object.status = self.object.STATUS_DISCARD
                my_route = KreditRoute.objects.create(
                    color='#d9534f',
                    kredit=self.object,
                    stage=0,
                    prev_group=prev_route.cur_group,
                    cur_group=prev_route.cur_group,
                    next_group=prev_route.next_group,
                    cur_user=request.user,
                    comment=request.POST.get('comment', ''),
                    session=request.POST.get('sess', '')
                )
                my_route.save()
                self.object.save(update_fields=['status'])
        return super(KreditDetail, self).post(request, *args, **kwargs)

    def get_success_url(self):
        return reverse_lazy('kredit_detail', kwargs={'pk': self.object.pk})


class KreditRequest(LoginRequiredMixin, SettingsToContext, BagesMixin, CreateView):
    template_name = 'kredit_request.html'
    model = Kredit
    form_class = KreditForm
    form2 = SessionFilesForm
    form_class_pref = 'kred'
    form2_pref = 'files'

    def get_context_data(self, **kwargs):
        context = super(KreditRequest, self).get_context_data(**kwargs)
        my_sess = uuid.uuid1()
        context['form'] = self.form_class(prefix=self.form_class_pref, initial={'sess': my_sess})
        context['form2'] = self.form2(prefix=self.form2_pref, initial={'sess': my_sess})
        return context

    def post(self, request, *args, **kwargs):
        form1 = self.form_class(data=request.POST,  prefix=self.form_class_pref)
        if form1.is_valid():
            kredit = form1.save(commit=False)
            kredit.user = request.user
            kredit.status = Kredit.STATUS_NEW
            kredit.save()
            if kredit.doc_complect == Kredit.FIRST_COMPLECT and len(Kredit.COMPLECT1) > 1:
                kredit.groups.add(Group.objects.get(name=Kredit.COMPLECT1[1]))
            if kredit.doc_complect == Kredit.SECOND_COMPLECT and len(Kredit.COMPLECT2) > 1:
                kredit.groups.add(Group.objects.get(name=Kredit.COMPLECT2[1]))
            kredit.save()
            messages.success(request, 'Kredit data successfully saved')
            return HttpResponseRedirect(reverse_lazy('kredit_detail', kwargs={'pk': kredit.id}))
        form2 = self.form2(data=request.POST, files=request.FILES, prefix=self.form2_pref)
        if form2.is_valid() and request.FILES:
            my_file = SessionFiles(path_to=request.FILES.get('file'), sess=request.POST.get('files-sess'))
            my_file.save()
            return super(KreditRequest, self).post(request, *args, **kwargs)
        return super(KreditRequest, self).post(request, *args, **kwargs)


class MyKredits(LoginRequiredMixin, SettingsToContext, BagesMixin, ListView):
    template_name = 'kredit_list.html'
    model = Kredit
    paginate_by = settings.UNITS_PER_PAGE

    def get_queryset(self):
        qs = None
        if self.kwargs.get('group', '') == settings.CREATOR_GROUP:
            qs = self.model.objects.filter(user=self.request.user)
        return qs


class SearchKredit(LoginRequiredMixin, SettingsToContext, BagesMixin, ListView):
    model = Kredit
    template_name = 'kredit_list.html'
    paginate_by = settings.UNITS_PER_PAGE

    def get_queryset(self):
        search_str = self.request.GET.get('searchstr', '')
        if search_str.isdigit():
            my_creds = self.model.objects.filter(id=search_str)
        else:
            my_creds = self.model.objects.filter(Q(name__istartswith=search_str)|Q(surname__istartswith=search_str))
        return my_creds

class GroupKredits(LoginRequiredMixin, SettingsToContext, BagesMixin, ListView):
    template_name = 'kredit_list.html'
    model = Kredit

    def get_queryset(self):
        my_group = self.kwargs.get('group')
        return self.model.objects.filter(groups__name=my_group).filter(status__in=[Kredit.STATUS_NEW, Kredit.STATUS_DONE])

kredit/templates/by_group.html
{% extends 'main_view.html' %}
{% load perm_checker %}
{% block addhead %}
    {{ block.super }}
{% endblock %}

{% block content %}
    {% for kredit in object_list %}
        {{ kredit.id }}
    {% endfor %}
{% endblock %}

{% block more_scripts %}
{% endblock %}

kredit/templates/kredit_detail.html
{% extends 'main_view.html' %}
 {% load i18n %}
 {% load staticfiles %}
 {% load perm_checker %}

{% block addhead %}
    {{ block.super }}
    <style xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
        [class^="file-"]{
            display: inline-block;
            background:url('{% static "img/file_sprite.png" %}');
            background-repeat: no-repeat;
            vertical-align: text-top;
            margin-right: 5px;
            width: 18px;
            height: 18px;
        }
        .file-folder { background:url('{% static "img/file_sprite.png" %}') right bottom no-repeat; }
        .file { background:url('./file_sprite.png') 0 0 no-repeat; }
        .file-pdf, .file-PDF { background-position: -18px 0 }
        .file-as { background-position: -36px 0 }
        .file-c { background-position: -72px -0px }
        .file-iso { background-position: -108px -0px }
        .file-htm, .file-html, .file-xml, .file-xsl { background-position: -126px -0px }
        .file-cf { background-position: -162px -0px }
        .file-cpp { background-position: -216px -0px }
        .file-cs { background-position: -236px -0px }
        .file-sql { background-position: -272px -0px }
        .file-xls, .file-xlsx, .file-csv, .file-xlsm { background-position: -362px -0px }
        .file-h { background-position: -488px -0px }
        .file-crt, .file-pem, .file-cer { background-position: -452px -18px }
        .file-php { background-position: -108px -18px }
        .file-jpg, .file-jpeg, .file-png, .file-gif, .file-bmp { background-position: -126px -18px }
        .file-ppt, .file-pptx { background-position: -144px -18px }
        .file-rb { background-position: -180px -18px }
        .file-text, .file-txt, .file-md, .file-log, .file-htaccess { background-position: -254px -18px;}
        .file-doc, .file-docx { background-position: -362px -18px }
        .file-zip, .file-gz, .file-tar, .file-rar { background-position: -416px -18px; }
        .file-js { background-position: -434px -18px }
        .file-css { background-position: -144px -0px }
        .file-fla { background-position: -398px -0px }
        .messages .warning { color: red; }
        .messages .success { color: darkgreen; }
        .kredit_status_D { color: red; font-weight: bold; }
        .kredit_status_A { color: green; font-weight: bold; }
        .my_info { margin-top: 10px; padding: 15px; color: #ffffff; font-weight: 700; }

        .userf { background-color: #f2f2f2; border-color: #e4e4e4; }
        .userfd { border-style: solid; border-width: 1px; border-color: #e4e4e4; }

        .kred_data { font-size: larger; }
        .kred_title { font-size: 16pt; font-weight: 600; }

        .block-heading-two h4 span {
            padding-bottom: 4px;
            border-bottom: 3px solid #32c8de;
            box-sizing: border-box;
        }

    .divider-10 {
        border-top: 1px solid #f1f1f1;
        border-bottom: 1px solid #e4e4e4;
        background: #f8f8f8;
        box-shadow: 0px 2px 5px rgba(0,0,0,0.05);
        padding: 2px;
        margin: 20px 0px;
    }
    .box-shadow-block {
        padding: 15px 20px;
        border: 1px solid #eee;
        background: #fff;
        border-top: 2px solid #32c8de;
    }
    .box-shadow-outer {
        position: relative;
        box-shadow: 0 2px 10px rgba(0, 0, 0, 0.2);
    }
    .media {
        border-left: 8px solid #32c8de;
        padding-left: 10px;
    }
    .media-heading {
        font-weight: 600;
    }
    .my-control {
        padding-bottom: 5px;
    }
    .my-btn { width: 250px;}

    </style>
    {{ form.media }}
{% endblock %}

{% block content %}
    <div style="padding-top:20px;"></div>
    <div class="box-shadow-outer">
        <div class="box-shadow-block">
            <div class="block-heading-two" style="padding-bottom: 20px;">
                <h4><span class="kred_title">{% trans 'Credit detail' %}</span></h4>
            </div>

            <div class="row">
                <div class="col-md-4 kred_data"><strong>{% trans "Office " %}</strong></div>
                <div class="col-md-4">{{ object.office }}</div>
            </div>

            <div class="row">
                <div class="col-md-4 kred_data"><strong>{% trans "Credit specialist " %}</strong></div>
                <div class="col-md-4">{{ object.user.first_name }}</div>
            </div>

            <div class="row">
                <div class="col-md-4 kred_data"><strong>{% trans "Date " %}</strong></div>
                <div class="col-md-4">{{ object.creation_date|date:"d.m.Y" }}</div>
            </div>

            <div class="row">
                <div class="col-md-4 kred_data"><strong>{% trans "Status " %}</strong></div>
                <div class="col-md-4">{{ object.get_status_display }}</div>
            </div>

            <div class="divider-10"></div>
            <div class="row">
                <div class="col-md-6 kred_title">{% trans 'Client' %}</div>
                <div class="col-md-6 kred_title">{% trans 'Credit data' %}</div>
            </div>
            <div class="row">
                <div class="col-md-2 kred_data"><strong>{% trans "Credit # " %}</strong></div>
                <div class="col-md-4">{{ object.id }}</div>

                <div class="col-md-2 kred_data"><strong>{% trans "Type " %}</strong></div>
                <div class="col-md-4">{{ object.get_kred_mode_display }}</div>
            </div>

            <div class="row">
                <div class="col-md-2 kred_data"><strong>{% trans "Name: " %}</strong></div>
                <div class="col-md-4">{{ object.name }}</div>

                <div class="col-md-2 kred_data"><strong>{% trans "Complect " %}</strong></div>
                <div class="col-md-4">{{ object.get_doc_complect_display }}</div>
            </div>

            <div class="row">
                <div class="col-md-2 kred_data"><strong>{% trans "SurName: " %}</strong></div>
                <div class="col-md-4">{{ object.surname }}</div>

                <div class="col-md-2 kred_data"><strong>{% trans "Sum " %}</strong></div>
                <div class="col-md-4">{{ object.sum }}</div>
            </div>


            <div class="row">
                <div class="col-md-2 kred_data"><strong>{% trans "Second Name: " %}</strong></div>
                <div class="col-md-4">{{ object.secondname }}</div>
            </div>

            <div class="row">
                <div class="col-md-2 kred_data"><strong>{% trans "Comment: " %}</strong></div>
                <div class="col-md-10">{{ object.kred_comment }}</div>
            </div>

            <div class="divider-10"></div>
            <h4>{% trans "Files" %}</h4>
            <div class="row">
                <div class="col-md-6">
                    <ul>
                    {% for file in files %}
                        <li><i class="file-{{ file.extension }}"></i>
                        <a href="{{ settings.MEDIA_URL }}{{ file.path_to }}">{{ file.path_to.name }}</a></li>
                    {% endfor %}
                    </ul>
                </div>
            </div>


            <div class="divider-10"></div>
            <h4>{% trans "History" %}</h4>
            <div class="row">
                <div class="col-md-12">
                    <ul class="media-list">
                        {% for route in routes %}
                        <li class="media" style="border-left: 8px solid {{ route.color }};">
                            <div class="media-body">
                                <div class="media-heading">{{ route.creation_date }}
                                    <span style="padding-left: 20px; font-weight: 100;">{{ route.cur_user.username }}</span></div>
                                <div style="font-style: italic;">{{ route.comment|safe }}</div>
                                <ul>
                                {% for fil in route.related_files %}
                                    <li><a href="{{ settings.MEDIA_URL }}{{ fil.path_to }}">{{ fil.path_to }}</a></li>
                                {% endfor %}
                                </ul>
                            </div>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>


        {% if not finish %}
             <div class="divider-10"></div>
            <h4>{% trans "Control" %}</h4>
        {% if request.user|has_group:object.get_cur_route.next_group.name and not request.user|has_group:object.get_cur_route.cur_group.name %}

         <div class="row">
                <div class="col-md-12 parent">
                    <div style="text-align: center">
                        <div style="display: inline-block; padding-bottom: 20px;">
                            <form method="post" action="#" id="credTake">
                                {% csrf_token %}
                                <input type="submit" name="takeButton" class="btn my-btn" style="font-weight: 600; color: white;  background-color: #d04bff;" value="{% trans 'Take it' %}"  form="credTake" />
                            </form>
                        </div>
                    </div>
                </div>
         </div>
        {% else %}
           <div class="row">
                <div class="col-md-9">
                   <form method="post" action="#" id="credComment">
                       {% csrf_token %}
                       {{ form.sess }}
                       {{ form.comment }}
                   </form>
               </div>
           </div>
           <div class="row">
                <div class="col-md-3">
                    {% if request.user|has_group:settings.FIRST_LINE_APPROVER %}
                    <div class="btn-group my-control">
                        <button type="button" class="btn btn-default  my-btn dropdown-toggle" data-toggle="dropdown">{% trans 'Transmit' %}
                        <span class="caret"></span></button>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="#">ДБ1</a></li>
                            <li><a href="#">ДБ2</a></li>
                            <li><a href="#">ДБ3</a></li>
                        </ul>
                    </div>
                    {% endif  %}

                    {% if request.user|has_group:settings.FIRST_LINE_APPROVER %}
                        <div class="my-control">
                            <input type="submit" name="declineButton" class="btn btn-danger my-btn" style="font-weight: 600;" value="{% trans 'Decline' %}" form="credComment" >
                        </div>
                    {% endif %}

                    {% if request.user|has_group:settings.FIRST_LINE_APPROVER %}
                        <div class="my-control">
                            <input type="submit" name="acceptButton" class="btn btn-success my-btn" style="font-weight: 600;" value="{% trans 'Accept' %}" form="credComment" >
                        </div>
                    {% endif %}

                    {% if request.user|has_group:settings.FIRST_LINE_APPROVER %}
                    <div class="my-control">
                        <input type="submit" name="improveButton" class="btn btn-warning my-btn" style="font-weight: 600;" value="{% trans 'Improve' %}" form="credComment" >
                    </div>
                    {% endif %}

                    <div class="my-control">
                        <input type="submit" name="commentButton" class="btn btn-info my-btn" style="font-weight: 600;" value="{% trans 'Commenting' %}" form="credComment"/>
                    </div>
                </div>
            </div>

            <div class="row" style="padding-top: 20px;">
                <div class="col-md-12">
                   <form method="post" action="#" name="credFiles" class="dropzone" id="my-dropzone">
                       {% csrf_token %}
                        {{ form.sess }}
                   </form>
                </div>
            </div>
        {% endif %}
        {% endif %}

        </div>
    </div>




    <div style="padding-top:20px;"></div>

{% endblock %}

{% block more_scripts %}
{% endblock %}

kredit/templates/my_kredits.html
{% extends 'main_layout.html' %}

{% block addhead %}

{% endblock %}

{% block main %}
{% endblock %}

{% block more_scripts %}
{% endblock %}

kredit/templates/search_kredit.html
{% extends 'main_layout.html' %}

{% block addhead %}

{% endblock %}

{% block main %}
{% endblock %}

{% block more_scripts %}
{% endblock %}